### PR TITLE
Separate data model related operations

### PR DESCRIPTION
**Pull request by ihemantd**
Please review the updates. Suggestions are most welcomed. 
Thanks,

### CODE REVIEW

**Comment by raysrashmi** [comment]
@ihemantd PR looks good. but i think you need to link "ConferenceDatastore" to rubyraven target.

We have two target "ConferecneApp" and "rubyraven"

**Comment by arunagw** [comment]
Nope. Right now we are not using `ConferenceApp` target inside app or apple store.

**Comment by ihemantd** [comment]
@arunagw Thanks for the clarification !

**Comment by arunagw** [comment]
Thanks for work and PR you are doing for this project.

**Comment by ihemantd** [comment]
Pleasure is mine, I am learning new things and very happy to work !

**Pull request merged**
